config/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
      path('admin/', admin.site.urls),
      
      path('', include('projectStore.urls')),
      
      path('contactus/', include('contactus.urls')),
      
      
     
]

contactus/urls.py
from django.urls import path
from .import views

app_name = "contactus"



urlpatterns = [
    path('', views.home),
    path('hire', views.hirewriter, name="hirewriter"),
    path('contactform/', views.contactuspage, name='contactform'),
]

projectStore/urls.py
from django.urls import path
from .import views 
from .views import ProjectDetail, Department


app_name ="projectStore"


urlpatterns = [
    path('', views.home, name='home'),
    
    path('projectList/', views.projectList, name="projectList"),

    path('hirewriter/', views.hirewriterform, name='hirewriter'),
    
    path('<slug:slug>/', ProjectDetail.as_view(), name='projectDetail'),
    
    path('department', views.department, name="department"),
    
    path('department/<str:depts>/', views.category, name='courses'),
    path('payment', views.payment, name='payment'),
    path('about', views.about, name='about'),
    
]

contactus/models.py
from django.db import models




TYPE_OF_WORK = (
    ('Article', 'Article'),
    ('Project', 'Educational Project'),
    ('Seminner', 'Seminner'),
    ('Other', 'Other'),
)

CLASIFICATION = (
    ('Post-graduate', 'Post-graduate'),
    ('undergraduate', 'Degree'),
    ('HND', 'Higher National Diploma'),
    ('ND', 'National Diploma'),
    ('NCE', 'Nigeria Certificate In Education'),
    
)

class HireWriter(models.Model):
    full_name = models.CharField(max_length=120)
    phone_number = models.CharField(max_length=11)
    email = models.EmailField(max_length=120)
    select_work_type = models.CharField(max_length=64, choices=TYPE_OF_WORK)
    clasification = models.CharField(max_length=64, choices=CLASIFICATION)
    job_discribtion = models.TextField()
    
    
    def __str__(self):
        return self.full_name
    
    

projectStore/models.py
from audioop import reverse
from pyexpat import model
from django.db import models
from django.urls import reverse



class Department(models.Model):
    name = models.CharField(max_length=120)
    slug = models.SlugField(max_length=120, unique=True)
       



    def __str__(self):
        return self.name
    
    class Meta:
        db_table = 'department'
        verbose_name = 'departments'

    def get_absolute_url(self):
        return reverse("projectStore:departmentDetail", args=[self.slug])



TYPE_OF_WORK = ( 
    ('article', 'Article'),
    ('project', 'Educational Project'),
    ('seminer', 'Seminer'),
    ('script', 'Scripts'),
)

class Project(models.Model):
    departments = models.ForeignKey(Department, related_name='projects', on_delete=models.CASCADE)
    topic = models.CharField(max_length=250,)
    slug = models.SlugField(max_length=250, unique=True)
    type_of_work = models.CharField(max_length=16, choices=TYPE_OF_WORK)
    pages = models.CharField(max_length=16)
    chapters = models.CharField(max_length=16)
    content = models.TextField()
    
    class Meta:
        ordering = ('topic',)
        index_together = (('id', 'slug'))
        
    def __str__(self):
        return "self. title" + "self.departments"
    
    def get_absolute_url(self):
        return reverse('projectStore:projectDetail', kwargs={'slug':self.slug})
    


class Contact(models.Model):
    name = models.CharField(max_length=250)
    subject = models.CharField(max_length=250)
    phone = models.CharField(max_length=11)
    email = models.EmailField()
    date = models.DateTimeField(auto_now_add=True)
    message = models.TextField()

    
    
    def __str__(self):
        return 'self.name' + 'self.title'
    
    class Meta:
        ordering = ('-date',)
    

projectStore/forms.py
from django import forms
from .models import Contact
from contactus .models import HireWriter


class ContactForm(forms.ModelForm):
    

    class Meta:
        model = Contact
        fields = ('__all__')
        


class HireWriterForm(forms.ModelForm):
    
    class Meta:
        model = HireWriter
        fields = ( '__all__')

contactus/views.py
from django.shortcuts import render
from projectStore.forms import ContactForm
from projectStore .views import Department

def home(request):
    return render(request, 'contactus/home.html')


def contactuspage(request):
    dept = Department.objects.all()

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            subject =form.cleaned_data['subject']
            phone = form.cleaned_data['phone']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            
            form.save()
            return render(request, 'contactus/success.html')
    form = ContactForm()
    context = {'form': form,
            'dept': dept}
    return render(request, 'contactus/contactform.html', context)







def hirewriter(request):
    return render(request, 'contactus/hire.html')

projectStore/views.py
from multiprocessing import context
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django .db .models import Q
from django.core.paginator import Paginator
from .forms import HireWriterForm
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView




def home(request):
    dept = Department.objects.all()
    context = {'dept': dept}
    return render(request, 'home.html', context)


def department(request):
    dept = Department.objects.all()
    context = {"dept": dept}
    return render(request, 'projectstore/department.html', context)

def category(request, depts):
    dept = Department.objects.all()
    category_project = Project.objects.filter(
        departments__name__contains=depts
    )
    context = {'depts': depts,
               'category_project':category_project,
               'dept': dept}
    return render(request, 'projectstore/courses.html', context)   



def projectList(request):
    dept = Department.objects.all()
    p = Paginator(Project.objects.all().order_by('?'), 10)
    page = request.GET.get('page') 
    list_of_project = p.get_page(page)
    context = {'list_of_project':list_of_project, 
               'dept': dept}
    return render(request, 'projectstore/list_of_all_project.html', context)




class ProjectDetail(DetailView):
    
    model = Project
    template_name = 'projectstore/project_detail.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    

def hirewriterform(request):
    
    dept = Department.objects.all()
    
    if request.method == 'POST':
        form = HireWriterForm(request.POST)
        if form.is_valid():
            full_name = form.cleaned_data['full_name']
            phone_number =form.cleaned_data['phone_number']
            email = form.cleaned_data['email']
            select_work_type = form.cleaned_data['select_work_type']
            clasification = form.cleaned_data['clasification']
            job_discribtion = form.cleaned_data['job_discribtion']
            
            
            form.save()
            return render(request, 'contactus/hire_success.html')
    form = HireWriterForm()
    context = {'form': form,
               'dept': dept}
    return render(request, 'projectstore/hirewriter.html', context)




def payment(request):
    dept = Department.objects.all()
    context = {'dept': dept}
    return render(request, 'projectstore/payment.html', context)


def about(request):
    dept = Department.objects.all()
    context = {'dept': dept}
    return render(request, 'projectstore/about.html', context)

contactus/templates/contactus/contactform.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block sidebar %}

<div class='d-flex mt-3 mb-2'>
    <form method="GET" action="{% url 'projectStore:projectList'%}" class="d-flex">
        <input class="form-control me-sm-2" name='q' type="text" placeholder="Search courses...">
    </form>
</div>
               

<div>
    <a class="text-decoration-none" href="{% url 'projectStore:department'%}">All Courses</a>
</div>
<hr>

<div>
    {% for department in dept  %}
    
        <div>
            <a class="text-decoration-none" href="{% url 'projectStore:courses' department.name  %}?q={{department.name}}">
                {{department.name}}
            </a>
        </div>
    {% endfor %}
</div>



{% endblock sidebar %}


{% block content %}

<form method="POST" action =''>
    {% csrf_token %}
    <div class="row">
        <div class="col-3">
        <div class="col-3 mt-2  mb-2">
            {{ form.name|as_crispy_field }}
        </div>
        <div class="col-3 mt-2  mb-2">
            {{ form.subject|as_crispy_field }}
        </div>
        <div class="col-3 mt-2  mb-2">
      
            {{ form.phone|as_crispy_field }}
        </div>
        <div class="col-3 mt-2  mb-2">
            {{ form.email|as_crispy_field }}
        </div>
            {{ form.message|as_crispy_field }}
            <div class="col-2 mt-2  mb-2">
            <button type = 'submit' class="btn btn-success"> Submit </button>
            </div>
        </div>
    </div>

</form>
{% endblock content %}











<h1>Contact Us</h1>
<h4>  Contact us directly if you have question  </h4>
<p>
    Please write your name, email address, phone number  and a message below if you have any questions.
    One of our staff members will be happy to contact you directly and answer your questions as soon as possible. 
</p>

contactus/templates/contactus/hire_success.html
{% extends "base.html" %}
<<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h3>thanks for showing intrest in our professional writers<h3>
            <p> we will contact you for further discussion on the provided email and phone number</p>
    </body>
</html>

projectStore/templates/projectstore/about.html
{% extends 'base.html' %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
      
        {% block sidebar %}
        
        
        <div class='d-flex mt-3 mb-2'>
            <form method="GET" action="{% url 'projectStore:projectList'%}" class="d-flex">
                <input class="form-control me-sm-2" name='q' type="text" placeholder="Search courses...">
            </form>
        </div>
                       

        <div>
            <a class="text-decoration-none" href="{% url 'projectStore:department'%}">All Courses</a>
        </div>
        <hr>

        <div>
            {% for department in dept  %}
            
                <div>
                    <a class="text-decoration-none" href="{% url 'projectStore:courses' department.name  %}?q={{department.name}}">
                        {{department.name}}
                    </a>
                </div>
            {% endfor %}
        </div>
        
        {% endblock sidebar %}





        
        {% block content %}
        <h1 class="text-center">ABOUT SOFTEDUPROJECT</h1>
        <hr>
        
        <h5>Welcome to Softeduproject</h5>
        Softeduproject assist final year students with quality, well researched, reliable and ready made project work. 
        Our materials are recent, complete (chapter 1 -5, with references) and well written.

        Simply select your department, choose from our list of topics available and fill in your data to download
        Getting Started
    <h6>How to use our service</h6>
        <ol>
            <li>Select a department</li>
            <li>Click on click on a topic under the department you have selected</li>
            <li>View the abstract and chapter 1 of the project work.</li>
        <li>Fill the form on the top left page</li>
        <li>You will receive your DOWNLOAD CODE and download full project, once the basic requirements has been met</li>
	<h6>Other Notes</h6>
        </ol>
        <p>	
<em>* All our materials are already written project work.</em><br>
	
<em>* Please do not submit or copy the projects you receive words to words.</em><br>
For further info</em>
07013445496
E-mail
cp4reallife@gmail.com
<br>
        </p>
<b>Disclaimer</b>
<p>
Softeduproject.com will only provide projects as a reference for your research. 
The projects ordered and produced should be used as a guide or framework for your own project.
 The contents of the projects should be able to help you in generating new ideas and thoughts 
 for your own project.</p>
<p>
 It is the aim of Softeduproject to only provide guidance by which the projects should be pursued.
We are neither encouraging any form of plagiarism nor are we advocating the use of the projects produced herein for cheating.
</p>

<h6><b>Terms and Condition</b></h6><br>
<p>
Using our service is LEGAL and IS NOT prohibited by any university/college policies. 
You are allowed to use the original model papers you will receive in the following ways:
<ul>

    <li>As a source for additional understanding of the subject</li>
    <li>As a source for ideas for you own research (if properly referenced)</li>
    <li>For PROPER paraphrasing ( see your university definition of plagiarism and acceptable paraphrase)
    Direct citing ( if referenced properly)</li>

Thank you so much for your respect to the authors copyright

    </p>
<h6><b>Copyright infringement or plagiarism</b><h6><br>

<p>
We take the intellectual property rights of others seriously and require that our customers 
and their end users do the same. If you believe we or someone has uploaded content to our 
website or service that infringes your copyright or your trademark,
 please let us know by sending us an infringement notice as described below.
  We will take appropriate actions
<h6>Copyright Notices:<h6><br>

For copyright notices, first you must either own a copyright or have authority to act on behalf of a copyright owner.
 If that’s the case, and you want to report a claim that a third party is infringing that material on 
 or through our website or service, please send a notice to us that includes all of the items below and we will take
  appropriate action:

    <li>Identification of the work or material being infringed.</li>
    <li>Identification of the material that is claimed to be infringing,<br> 
        including its Project Id, with sufficient detail so that projectng is 
        capable of finding it and verifying its existence.</li>
    <li>Contact information for the notifying party, including name, address, telephone number and e-mail address.</li>
    <li>A statement that the notifying party has a good faith belief that the material is not authorized by the copyright owner,
         <br>its agent or law.</li>
   <li> A physical or electronic signature of a person authorized to act on behalf of the owner of the copyright that has
     been allegedly infringed.</li>

Please send these claims to: cp4reallife@gmail.com
        {% endblock content %}
    </body>
</html>

projectStore/templates/projectstore/department.html
{% extends 'base.html' %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        
        
        {% block sidebar %}

        <div>
            <a class="text-decoration-none" href="{% url 'projectStore:department'%}">All Courses</a>
        </div>
        <hr>

        <div>
            {% for department in dept  %}
            
                <div>
                    <a class="text-decoration-none" href="{% url 'projectStore:courses' department.name  %}?q={{department.name}}">{{department.name}}</a>
                </div>

            {% endfor %}


        </div>
        {% endblock sidebar %}


        <!--Start of Main content-->
        {% block content %}
    
        <div class="row">
            <div class="col-12">
                <div class="card bg-light ms-4 mc-4 mb-4 ">
                    <div class="card-header d-flex justify-content-center">LIST OF DEPARMENTS & COURSES </div>
                        <div class="card-body">
                            <h4 class="card-title d-flex justify-content-center ">COURSES </h4>
                        <!--looping through List of Departments-->
                        {% for department in dept  %}
                        <p class="card-text">
                         <li class="list-unstyled list-group-item d-flex justify-content- aling-items-center">
                            
                        <a class="text-decoration-none" href="{% url 'projectStore:courses' department.name %}"> <p>{{department.name}}</p></a>
                    {% endfor %}
                            <!--End of Loop-->
                        </div>
                
                    
                </div>
            </div>
        
        </div>
        {% endblock content %}
        
        <!--End Of Main content-->
    
    </body>
</html>

projectStore/templates/projectstore/hirewriter.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        
        {% block sidebar %}
        
        
        <div>
            <a class="text-decoration-none" href="{% url 'projectStore:department'%}">All Courses</a>
        </div>
        <hr>

        <div>
            {% for department in dept  %}
            
                <div>
                    <a class="text-decoration-none" href="{% url 'projectStore:courses' department.name  %}?q={{department.name}}">{{department.name}}</a>
                </div>
                
            {% endfor %}


        </div>
        
        {% endblock sidebar %}





    
        {% block content %}

<form method="POST" action =''>
    {% csrf_token %}
    <div class="row">
        <div class="col-3">
        <div class="col-3 mt-1  mb-2">
            {{ form.full_name|as_crispy_field }}
        </div>
        <div class="col-3 mt-1  mb-2">
            {{ form.phone_number|as_crispy_field }}
        </div>
        <div class="col-3 mt-1  mb-2">
      
            {{ form.email|as_crispy_field }}
        </div>
        <div class="col-3 mt-2  mb-2">
            {{ form.select_work_type|as_crispy_field }}
        </div>

        <div class="col-3 mt-2  mb-2">
            {{ form.clasification|as_crispy_field }}
        </div>
            {{ form.job_discribtion|as_crispy_field }}
            <div class="col-2 mt-2  mb-2">
            <button type = 'submit' class="btn btn-success"> Submit </button>
            </div>
        </div>
    </div>

</form>
        {% endblock content %}

    </body>
</html>

projectStore/templates/projectstore/list_of_all_project.html
{% extends "base.html" %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
    </head>
    <body>  

        <!--Begging of Sidebar -->
        
    <body>


        {% block sidebar %}
            <div class='d-flex mt-3 mb-2'>
                <form method="GET" action="{% url 'projectStore:projectList'%}" class="d-flex">
                    <input class="form-control me-sm-2" name='q' type="text" placeholder="Search courses...">
                </form>
            </div>
                           

            <div>
                <a class="text-decoration-none" href="{% url 'projectStore:department'%}">All Courses</a>
            </div>
            <hr>

            <div>
                {% for department in dept  %}
                
                    <div>
                        <a class="text-decoration-none" href="{% url 'projectStore:courses' department.name  %}?q={{department.name}}">
                            {{department.name}}
                        </a>
                    </div>
                {% endfor %}
            </div>
            {% endblock sidebar %}
        <!--End of Sidebar-->




        <!--Begging of Main content-->
        {% block content %}

        <div class="card bg-light ms-4 mc-4 mb-4 min-vh-100">
            <div class="card-header d-flex justify-content-center">THOUSANDS OF RESEARCH PROJECT TOPICS ON EDUCATION</div>
            <div class="card-body">
                <h4 class="card-title d-flex justify-content-center ">Project Topics </h4>

            
            <!--looping through the list of project Topics-->
                {% for project in list_of_project  %}
            <p class="card-text">
                <li class="list-unstyled list-group-item d-flex justify-content- aling-items-center">
                    
                    <a class="text-decoration-none" href="{{project.get_absolute_url}}">         
                        {{project.topic}}
                        <p>{{ project.content | slice:":400" }}...</p>
                    </a>
                </li>
            </p>

                <div class="text">
                    <small>{{project.department.name}}</small>
                </div>

                <small>
                    {{project.type_of_work}} |
                    numbers of Pages: {{project.pages}} |
                    Numbers of Chapter: {{project.chapters}}
                    
                </small>
        
            <hr>
            
            {% endfor %}
            <!--end of loop for the  list of project-->
              <nav aria-label="Page navigation example">
                <ul class="pagination">

            {% if list_of_project.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo First Page</a></li>
            <li class="page-item"><a class="page-link" href="?page={{list_of_project.previous_page_number}}">Previouse Page</a></li>
            
            {% endif %}

            <li class="page-item disabled"><a class="page-link " href="#"> Page{{list_of_project.number}} of {{list_of_project.paginator.num_pages}}</a></li>

            {% if list_of_project.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{list_of_project.next_page_number}}">Next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{list_of_project.paginator.num_pages}}">Last Page &raquo</a></li>
            
            {% endif %}
        </ul>
    </nav>
        </div>

            
        {% endblock content %}
   <!--End of main content-->
    </body>
</html>

projectStore/templates/projectstore/payment.html
{% extends 'base.html' %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
      
        {% block sidebar %}
        
        
        <div class='d-flex mt-3 mb-2'>
            <form method="GET" action="{% url 'projectStore:projectList'%}" class="d-flex">
                <input class="form-control me-sm-2" name='q' type="text" placeholder="Search courses...">
            </form>
        </div>
                       

        <div>
            <a class="text-decoration-none" href="{% url 'projectStore:department'%}">All Courses</a>
        </div>
        <hr>

        <div>
            {% for department in dept  %}
            
                <div>
                    <a class="text-decoration-none" href="{% url 'projectStore:courses' department.name  %}?q={{department.name}}">
                        {{department.name}}
                    </a>
                </div>
            {% endfor %}
        </div>
        
        {% endblock sidebar %}





        
        {% block content %}
        
        
        <h4>Payment Mode</h4>
        <p class="card-text">


  We are happy to offer instant delivery of projects listed on our website. 
  After making your payment. Text OR WhatsApp us the following details:
      <ol>
          <li>Payee Name</li>
          <li>Transfer Ref NO.</li>
          <li>Amount paid</li>
          <li>Payment Date</li>
          <li>project title to be downloaded</li>
          <li>Email</li> OR
          <li>WhatsApp Contact</li>                                   
      </ol>
      After recieveing and confirming this details from you. Then expect the project material with 30 to 45 minite same day
      </p>
      <P>
        <hr>
        <h5>ACCOUNT DETAILS</h5>
        <br>
            Bank: United Bank Of Africa (UBA) <br>
            Acount Name: OGBU CYPRIAN OMOHA<br>
            Account Number: 2079637279<br>

      </P>
      <hr>
      <h5>  USSD Transfer  </h5>
      you can still choose to Transfer using USSD. after a successfull Transfer
      send use details of payment. 
      <hr>
      <h5>Instant CARD Payment</h5>
      <h6>Coming soon...</h6>
        {% endblock content %}
    </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    </head>

    <body class="d-flex flex-column min-vh-100">
        <header>
            {% include 'nav.html' %}
        </header>
            <div class="container-fluid">
                    <div class="row">

<!--SIDEBAR BEGING-->

                    <div class="col-2">
                        <div class='d-flex mt-3 mb-2'>
                            <form method="GET" action="{% url 'projectStore:projectList'%}" class="d-flex">
                                <input class="form-control me-sm-2" name='q' type="text" placeholder="Search courses...">
                            </form>
                        </div>

                        <div>
                            <a href="{% url 'projectStore:department'%}">All Courses</a>
                        </div>
                        <hr>

                        {% for department in dept  %}
                
                        <div>
                            <a href="{% url 'projectStore:courses' department.name  %}?q={{department.name}}">{{department.name}}</a>
                        </div>
                         {% endfor %}
                    </div>
        

<!--MAIN CONTENT BEGING-->
                    <div class="col-md-10">

                        {% block content %}
            

                    





                        {% endblock content %}                
                
                    </div>
<!--MAIN CONTENT END-->

<!--FOOTER BEGING-->
                <div >
                    {% include 'footer.html' %}
                </div>
<!--FOOTER END-->
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
            </div>
    </div>
    </body>
</html>

templates/nav.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  </head>
  <body>
   
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'projectStore:home' %}">SoftEduProject</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'projectStore:home' %}">Home
              <span class="visually-hidden">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'projectStore:projectList'%}">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'projectStore:department'%}">Departments</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'projectStore:hirewriter'%}">Hirw A Writer</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'projectStore:payment'%}">Payment</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contactus:contactform'%}">Contact Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'projectStore:about'%}">About Us</a>
          </li>
          </ul>
        <form class="d-flex" method="GET" action="{% url 'projectStore:projectList'%}">
          <input class="form-control me-sm-2" type="text" name='q' placeholder="Search">
    
        </form>
      </div>
    </div>
  </nav>
  

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

  </body>
</html>

  